---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "danebot.fullname" . }}
spec:
  schedule: "{{ .Values.jobSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: {{ include "danebot.fullname" . }}
          serviceAccountName: {{ include "danebot.fullname" . }}
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            name: danebot
            command: ["/bin/sh", "-c"]
            args:
              - /app/dane.sh
            volumeMounts:
            - mountPath: /etc/letsencrypt
              name: danebot
            envFrom:
            - secretRef:
                {{- if .Values.secret.existingSecret }}
                name: {{ .Values.secret.existingSecret }}
                {{- else }}
                name: {{ include "danebot.fullname" . }}-keys
                {{- end }}
          restartPolicy: Never
          {{- with .Values.dnsPolicy }}
          dnsPolicy: {{ . }}
          {{- end }}
          {{- with .Values.dnsConfig }}
          dnsConfig:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: danebot
            persistentVolumeClaim:
              claimName: {{ include "danebot.fullname" . }}

