{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "danebot.fullname" . }}-keys
  labels:
    {{- include "danebot.labels" . | nindent 4 }}
stringData:
  {{- .Values.secret.contents | nindent 2 }}
{{- end }}
