apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "danebot.fullname" . }}
  annotations:
  {{- with .Values.serviceAccount.annotations  }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "danebot.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "danebot.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
